#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Nov  9 05:02:56 2023
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from Ui_MainWindow import Ui_MainWindow


class App(wx.App):
    def OnInit(self):
        self.MainWindow = Ui_MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MainWindow)
        self.MainWindow.Show()
        return True

# end of class App

if __name__ == "__main__":
    app = App(0)
    app.MainLoop()
