#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun Jan 14 21:12:05 2024
#

import wx

import wx.adv

import widgets.table_view
import widgets.relation_selector
import widgets.supplied_data_editor
import widgets.tree_view
import widgets.supplied_data_viewer


class Ui_DischargeSeries_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((797, 425))
        self.SetTitle(u"Список серий замеров")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.list_container = wx.BoxSizer(wx.VERTICAL)

        self.list = widgets.table_view.TableView(self.panel_1, wx.ID_ANY)
        self.list_container.Add(self.list, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.list_container)

        self.Layout()
        self.Centre()


class Ui_DischargeMeasurement_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((442, 564))
        self.SetTitle(u"Добавление/Редактирование поразгрузочных замеров")

        self.window_1 = wx.SplitterWindow(self, wx.ID_ANY, style=0)
        self.window_1.SetMinimumPaneSize(40)
        self.window_1.SetSashGravity(1.0)

        self.window_1_pane_1 = wx.ScrolledWindow(self.window_1, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.window_1_pane_1.SetScrollRate(10, 10)

        sizer_2 = wx.FlexGridSizer(1, 1, 5, 5)

        sizer_4 = wx.WrapSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 0, wx.ALL, 10)

        grid_sizer_1 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.TOP, 10)

        label_41 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "ID:")
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_42 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Серия:")
        label_42.SetToolTip(u"Привязка к серии замеров")
        grid_sizer_1.Add(label_42, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DSID = widgets.relation_selector.RelationSelector(self.window_1_pane_1, wx.ID_ANY)
        grid_sizer_1.Add(self.field_DSID, 1, wx.EXPAND, 0)

        label_43 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Замер №:")
        label_43.SetToolTip(u"Порядковый номер замера.")
        grid_sizer_1.Add(label_43, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_SNumber = wx.SpinCtrl(self.window_1_pane_1, wx.ID_ANY, "", min=1, max=1000000000)
        grid_sizer_1.Add(self.field_SNumber, 0, 0, 0)

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"Образец керна"), wx.HORIZONTAL)
        sizer_4.Add(sizer_9, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_10 = wx.FlexGridSizer(6, 2, 5, 5)
        sizer_9.Add(grid_sizer_10, 1, wx.BOTTOM | wx.TOP, 10)

        label_44 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Рег. № разгрузки:")
        label_44.SetToolTip(u"Регистрационный номер разгрузки")
        grid_sizer_10.Add(label_44, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DschNumber = wx.TextCtrl(self.window_1_pane_1, wx.ID_ANY, "")
        self.field_DschNumber.SetMinSize((190, 23))
        grid_sizer_10.Add(self.field_DschNumber, 0, 0, 0)

        label_60 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Рег. № керна:")
        label_60.SetToolTip(u"Регистрационный номер образца керна")
        grid_sizer_10.Add(label_60, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreNumber = wx.TextCtrl(self.window_1_pane_1, wx.ID_ANY, "")
        self.field_CoreNumber.SetMinSize((200, 23))
        grid_sizer_10.Add(self.field_CoreNumber, 0, 0, 0)

        label_61 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"⌀ керна, мм:")
        label_61.SetToolTip(u"Диаметр образца керна")
        grid_sizer_10.Add(label_61, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Diameter = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Diameter.SetDigits(2)
        grid_sizer_10.Add(self.field_Diameter, 0, 0, 0)

        label_64 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"L образца керна, мм:")
        label_64.SetToolTip(u"Длина образца керна")
        grid_sizer_10.Add(label_64, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Length = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Length.SetDigits(2)
        grid_sizer_10.Add(self.field_Length, 0, 0, 0)

        label_65 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Вес керна, г:")
        label_65.SetToolTip(u"Вес образца керна")
        grid_sizer_10.Add(label_65, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Weight = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Weight.SetDigits(2)
        grid_sizer_10.Add(self.field_Weight, 0, 0, 0)

        label_66 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"H взятия образца керна, м:")
        label_66.SetToolTip(u"Глубина взятия образца керна, м")
        grid_sizer_10.Add(label_66, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreDepth = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_CoreDepth.SetDigits(2)
        grid_sizer_10.Add(self.field_CoreDepth, 0, 0, 0)

        sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"Параметры тензодатчиков"), wx.VERTICAL)
        sizer_4.Add(sizer_11, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_12 = wx.GridBagSizer(5, 5)
        sizer_11.Add(grid_sizer_12, 1, wx.BOTTOM | wx.TOP, 10)

        label_57 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Тензопатрон №:")
        label_57.SetToolTip(u"Номер партии тензодатчиков")
        label_57.Wrap(100)
        grid_sizer_12.Add(label_57, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CartNumber = wx.TextCtrl(self.window_1_pane_1, wx.ID_ANY, "")
        self.field_CartNumber.SetMinSize((200, 23))
        grid_sizer_12.Add(self.field_CartNumber, (0, 1), (1, 1), 0, 0)

        label_58 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Партия тензодатчиков №:")
        label_58.SetToolTip(u"Номер партии тензодатчиков")
        grid_sizer_12.Add(label_58, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PartNumber = wx.TextCtrl(self.window_1_pane_1, wx.ID_ANY, "")
        self.field_PartNumber.SetMinSize((200, 23))
        grid_sizer_12.Add(self.field_PartNumber, (1, 1), (1, 1), 0, 0)

        sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"Сопротивление тензорезистора, Ом"), wx.HORIZONTAL)
        sizer_11.Add(sizer_12, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_11 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_12.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_20.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 1")
        grid_sizer_11.Add(label_20, 0, wx.ALIGN_BOTTOM, 0)

        label_21 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_21.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 2")
        grid_sizer_11.Add(label_21, 0, wx.ALIGN_BOTTOM, 0)

        label_22 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "3")
        label_22.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 1")
        grid_sizer_11.Add(label_22, 0, wx.ALIGN_BOTTOM, 0)

        label_23 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "4")
        label_23.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 2")
        grid_sizer_11.Add(label_23, 0, wx.ALIGN_BOTTOM, 0)

        self.field_R1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=1000.0)
        self.field_R1.SetDigits(1)
        grid_sizer_11.Add(self.field_R1, 0, wx.EXPAND, 0)

        self.field_R2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=1000.0)
        self.field_R2.SetDigits(1)
        grid_sizer_11.Add(self.field_R2, 0, wx.EXPAND, 0)

        self.field_R3 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=1000.0)
        self.field_R3.SetDigits(1)
        grid_sizer_11.Add(self.field_R3, 0, wx.EXPAND, 0)

        self.field_R4 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=1000.0)
        self.field_R4.SetDigits(1)
        grid_sizer_11.Add(self.field_R4, 0, wx.EXPAND, 0)

        grid_sizer_14 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_11.Add(grid_sizer_14, 1, 0, 0)

        label_212 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Ω компенсаторного резистора, Ом:")
        label_212.SetToolTip(u"Сопротивление компенсационного резистора")
        grid_sizer_14.Add(label_212, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_RComp = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_RComp.SetDigits(2)
        grid_sizer_14.Add(self.field_RComp, 0, 0, 0)

        label_213 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Коэф. чувств. тензодатчиков:")
        label_213.SetToolTip(u"Коэффициент чувствительности тензодатчиков")
        grid_sizer_14.Add(label_213, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Sensitivity = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Sensitivity.SetDigits(2)
        grid_sizer_14.Add(self.field_Sensitivity, 0, 0, 0)

        sizer_10 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"Тензометрия"), wx.VERTICAL)
        sizer_4.Add(sizer_10, 1, wx.BOTTOM | wx.EXPAND, 10)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"t прохождения продольных волн (ультразв. проф. или др.), мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_5, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_4 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_5.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        label_25 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_25.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_4.Add(label_25, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        label_26 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_26.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_4.Add(label_26, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TP_1_1_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_1_1_enabled, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_TP_1_1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TP_1_1.Enable(False)
        self.field_TP_1_1.SetDigits(2)
        grid_sizer_4.Add(self.field_TP_1_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TP_1_2_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_1_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TP_1_2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TP_1_2.Enable(False)
        self.field_TP_1_2.SetDigits(2)
        grid_sizer_4.Add(self.field_TP_1_2, 0, wx.EXPAND | wx.RIGHT, 5)

        sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"t прохождения продольных волн (между торцами или др.), мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_13, 1, wx.EXPAND, 0)

        grid_sizer_13 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_13.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        grid_sizer_13.Add((0, 0), 0, 0, 0)

        label_27 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_27.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_13.Add(label_27, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_13.Add((0, 0), 0, 0, 0)

        label_28 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_28.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_13.Add(label_28, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TP_2_1_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_13.Add(self.field_TP_2_1_enabled, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_TP_2_1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TP_2_1.Enable(False)
        self.field_TP_2_1.SetDigits(2)
        grid_sizer_13.Add(self.field_TP_2_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TP_2_2_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_13.Add(self.field_TP_2_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TP_2_2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TP_2_2.Enable(False)
        self.field_TP_2_2.SetDigits(2)
        grid_sizer_13.Add(self.field_TP_2_2, 0, wx.EXPAND | wx.RIGHT, 5)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"t прохождения поверхностных волн, мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_6, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        grid_sizer_5 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_6.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        label_24 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_24.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_5.Add(label_24, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        label_13 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_13.SetToolTip(u"Замер времени прохождения поверхностных волн - 2")
        grid_sizer_5.Add(label_13, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TR_1_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.field_TR_1_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TR_1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TR_1.Enable(False)
        self.field_TR_1.SetDigits(2)
        grid_sizer_5.Add(self.field_TR_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TR_2_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.field_TR_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TR_2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TR_2.Enable(False)
        self.field_TR_2.SetDigits(2)
        grid_sizer_5.Add(self.field_TR_2, 0, wx.EXPAND, 0)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"t прохождения поперечных волн, мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_7, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        grid_sizer_6 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_7.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        label_14 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_14.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_6.Add(label_14, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        label_15 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_15.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_6.Add(label_15, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TS_1_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.field_TS_1_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TS_1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TS_1.Enable(False)
        self.field_TS_1.SetDigits(2)
        grid_sizer_6.Add(self.field_TS_1, 0, wx.EXPAND, 0)

        self.field_TS_2_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.field_TS_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TS_2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=999.0)
        self.field_TS_2.Enable(False)
        self.field_TS_2.SetDigits(2)
        grid_sizer_6.Add(self.field_TS_2, 0, wx.EXPAND, 0)

        grid_sizer_7 = wx.FlexGridSizer(2, 3, 5, 5)
        sizer_4.Add(grid_sizer_7, 1, wx.BOTTOM | wx.EXPAND, 10)

        label_54 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Статич. коэф. Пуассона:")
        label_54.SetToolTip(u"Статический коэффициент Пуассона")
        grid_sizer_7.Add(label_54, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PuassonStatic_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_7.Add(self.field_PuassonStatic_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_PuassonStatic = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_PuassonStatic.Enable(False)
        self.field_PuassonStatic.SetDigits(2)
        grid_sizer_7.Add(self.field_PuassonStatic, 0, 0, 0)

        label_55 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Cтатич. модуль Юнга:")
        label_55.SetToolTip(u"Статический модуль Юнга")
        grid_sizer_7.Add(label_55, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_YungStatic_enabled = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "")
        grid_sizer_7.Add(self.field_YungStatic_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_YungStatic = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_YungStatic.Enable(False)
        self.field_YungStatic.SetDigits(2)
        grid_sizer_7.Add(self.field_YungStatic, 0, 0, 0)

        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, u"Относительная деформация образца"), wx.HORIZONTAL)
        sizer_4.Add(sizer_8, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_8 = wx.GridSizer(2, 4, 5, 5)
        sizer_8.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "1")
        label_16.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 1")
        grid_sizer_8.Add(label_16, 0, wx.ALIGN_BOTTOM, 0)

        label_17 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "2")
        label_17.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 2")
        grid_sizer_8.Add(label_17, 0, wx.ALIGN_BOTTOM, 0)

        label_18 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "3")
        label_18.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 1")
        grid_sizer_8.Add(label_18, 0, wx.ALIGN_BOTTOM, 0)

        label_19 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "4")
        label_19.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 2")
        grid_sizer_8.Add(label_19, 0, wx.ALIGN_BOTTOM, 0)

        self.field_E1 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=-999.0, max=999.0)
        self.field_E1.SetDigits(2)
        grid_sizer_8.Add(self.field_E1, 0, wx.EXPAND, 0)

        self.field_E2 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=-999.0, max=999.0)
        self.field_E2.SetDigits(2)
        grid_sizer_8.Add(self.field_E2, 0, wx.EXPAND, 0)

        self.field_E3 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=-999.0, max=999.0)
        self.field_E3.SetDigits(2)
        grid_sizer_8.Add(self.field_E3, 0, wx.EXPAND, 0)

        self.field_E4 = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=-999.0, max=999.0)
        self.field_E4.SetDigits(2)
        grid_sizer_8.Add(self.field_E4, 0, wx.EXPAND, 0)

        grid_sizer_9 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_4.Add(grid_sizer_9, 1, wx.BOTTOM | wx.EXPAND, 10)

        label_62 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Угол коррекции направления напряжений, α°:", style=wx.ALIGN_RIGHT)
        label_62.SetToolTip(u"Угол коррекции направления напряжений, α°")
        label_62.Wrap(150)
        grid_sizer_9.Add(label_62, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Rotate = wx.SpinCtrlDouble(self.window_1_pane_1, wx.ID_ANY, initial=0.0, min=-90.0, max=90.0)
        self.field_Rotate.SetDigits(2)
        grid_sizer_9.Add(self.field_Rotate, 0, 0, 0)

        label_63 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, u"Тип породы:")
        label_63.SetToolTip(u"Тип породы")
        grid_sizer_9.Add(label_63, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RockType = wx.TextCtrl(self.window_1_pane_1, wx.ID_ANY, "")
        self.field_RockType.SetMinSize((200, 23))
        grid_sizer_9.Add(self.field_RockType, 0, 0, 0)

        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_14 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_14, 0, wx.ALIGN_RIGHT | wx.ALL, 10)

        self.button_Cancel = wx.Button(self.window_1_pane_2, wx.ID_ANY, u"Отмена")
        sizer_14.Add(self.button_Cancel, 0, wx.RIGHT, 5)

        self.button_Save = wx.Button(self.window_1_pane_2, wx.ID_ANY, u"Сохранить")
        sizer_14.Add(self.button_Save, 0, 0, 0)

        sizer_14.Realize()

        self.window_1_pane_2.SetSizer(sizer_1)

        grid_sizer_6.AddGrowableCol(1)
        grid_sizer_6.AddGrowableCol(3)

        grid_sizer_5.AddGrowableCol(1)
        grid_sizer_5.AddGrowableCol(3)

        grid_sizer_13.AddGrowableCol(1)
        grid_sizer_13.AddGrowableCol(3)

        grid_sizer_4.AddGrowableCol(1)
        grid_sizer_4.AddGrowableCol(3)

        grid_sizer_11.AddGrowableCol(0)
        grid_sizer_11.AddGrowableCol(1)
        grid_sizer_11.AddGrowableCol(2)
        grid_sizer_11.AddGrowableCol(3)

        grid_sizer_1.AddGrowableCol(1)

        sizer_2.AddGrowableRow(0)
        sizer_2.AddGrowableCol(0)
        self.window_1_pane_1.SetSizer(sizer_2)

        self.window_1.SplitHorizontally(self.window_1_pane_1, self.window_1_pane_2, 490)

        self.Layout()
        self.Centre()


class Ui_MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((973, 817))
        self.SetTitle(u"Геомеханика - Поразгрузочные замеры")
        self.SetToolTip(u"БД Геомеханика")

        # Menu Bar
        self.MainWindow_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu_sub = wx.Menu()
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Поразгрузочный замер", "")
        self.Bind(wx.EVT_MENU, self._on_create_discharge_measurement, item)
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Серию поразгрузочных замеров", "")
        self.Bind(wx.EVT_MENU, self._on_create_discharge_series, item)
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Скважину", "")
        self.Bind(wx.EVT_MENU, self._on_create_bore_hole, item)
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Горный объект", "")
        self.Bind(wx.EVT_MENU, self._on_create_mine_object, item)
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Оригинальный набор образцов", "")
        self.Bind(wx.EVT_MENU, self._on_create_orig_sample_sets, item)
        wxglade_tmp_menu.Append(wx.ID_ANY, u"Создать", wxglade_tmp_menu_sub, "")
        wxglade_tmp_menu.AppendSeparator()
        self.MainWindow_menubar._show_discharge_series = wxglade_tmp_menu.Append(wx.ID_ANY, u"Серии замеров", u"Показать список серий замеров")
        self.Bind(wx.EVT_MENU, self._on_show_discharge_series, self.MainWindow_menubar._show_discharge_series)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Горные обьекты", "")
        self.Bind(wx.EVT_MENU, self._on_show_mine_object, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Скважины", "")
        self.Bind(wx.EVT_MENU, self._on_show_bore_holes, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Оригинальные наборы образцов", "")
        self.Bind(wx.EVT_MENU, self._on_show_orig_sample_sets, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Системы координат", "")
        self.Bind(wx.EVT_MENU, self._on_show_coord_system, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Cтанции", "")
        self.Bind(wx.EVT_MENU, self._on_show_stations, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Настройки", "")
        self.Bind(wx.EVT_MENU, self._on_show_settings, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Выйти", "")
        self.Bind(wx.EVT_MENU, self._on_exit, item)
        self.MainWindow_menubar.Append(wxglade_tmp_menu, u"Файл")
        self.SetMenuBar(self.MainWindow_menubar)
        # Menu Bar end

        self.window_1_pane_1 = wx.Panel(self, wx.ID_ANY)

        self.list_container = wx.BoxSizer(wx.VERTICAL)

        self.list = widgets.table_view.TableView(self.window_1_pane_1, wx.ID_ANY)
        self.list_container.Add(self.list, 1, wx.EXPAND, 0)

        self.window_1_pane_1.SetSizer(self.list_container)

        self.Layout()
        self.Centre()


    def _on_create_discharge_measurement(self, event):
        print("Event handler '_on_create_discharge_measurement' not implemented!")
        event.Skip()

    def _on_create_discharge_series(self, event):
        print("Event handler '_on_create_discharge_series' not implemented!")
        event.Skip()

    def _on_create_bore_hole(self, event):
        print("Event handler '_on_create_bore_hole' not implemented!")
        event.Skip()

    def _on_create_mine_object(self, event):
        print("Event handler '_on_create_mine_object' not implemented!")
        event.Skip()

    def _on_create_orig_sample_sets(self, event):
        print("Event handler '_on_create_orig_sample_sets' not implemented!")
        event.Skip()

    def _on_show_discharge_series(self, event):
        print("Event handler '_on_show_discharge_series' not implemented!")
        event.Skip()

    def _on_show_mine_object(self, event):
        print("Event handler '_on_show_mine_object' not implemented!")
        event.Skip()

    def _on_show_bore_holes(self, event):
        print("Event handler '_on_show_bore_holes' not implemented!")
        event.Skip()

    def _on_show_orig_sample_sets(self, event):
        print("Event handler '_on_show_orig_sample_sets' not implemented!")
        event.Skip()

    def _on_show_coord_system(self, event):
        print("Event handler '_on_show_coord_system' not implemented!")
        event.Skip()

    def _on_show_stations(self, event):
        print("Event handler '_on_show_stations' not implemented!")
        event.Skip()

    def _on_show_settings(self, event):
        print("Event handler '_on_show_settings' not implemented!")
        event.Skip()

    def _on_exit(self, event):
        print("Event handler '_on_exit' not implemented!")
        event.Skip()


class Ui_DischargeSeries_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((469, 504))
        self.SetTitle(u"Создание/Редактирование \"Набор замеров\"")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_4 = wx.FlexGridSizer(2, 1, 0, 0)

        grid_sizer_1 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 10)

        label_41 = wx.StaticText(self.panel_1, wx.ID_ANY, "ID:")
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.panel_1, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, (0, 2), (1, 1), wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Рег. №")
        grid_sizer_1.Add(label_1, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Number = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_Number.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Number, (1, 2), (1, 1), wx.EXPAND, 0)

        label_42 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Название:")
        label_42.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_42, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_Name.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Name, (2, 2), (1, 1), wx.EXPAND, 0)

        label_43 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Комментарий:")
        label_43.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_43, (3, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, (3, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.SetMinSize((200, 46))
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, (3, 2), (1, 1), wx.EXPAND, 0)

        label_44 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Исходный набор образцов:")
        label_44.SetToolTip(u"Внутренний идентификатор замера")
        label_44.Wrap(150)
        grid_sizer_1.Add(label_44, (4, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_OSSID = widgets.relation_selector.RelationSelector(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.field_OSSID, (4, 2), (1, 1), wx.EXPAND, 0)

        label_45 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Дата проведения измерений:")
        label_45.SetToolTip(u"Внутренний идентификатор замера")
        label_45.Wrap(150)
        grid_sizer_1.Add(label_45, (5, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_MeasureDate = wx.adv.DatePickerCtrl(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.field_MeasureDate, (5, 2), (1, 1), 0, 0)

        sizer_1 = wx.StdDialogButtonSizer()
        sizer_4.Add(sizer_1, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.LEFT | wx.RIGHT, 10)

        self.button_CANCEL = wx.Button(self.panel_1, wx.ID_ANY, u"Отмена")
        sizer_1.Add(self.button_CANCEL, 0, wx.RIGHT, 5)

        self.button_SAVE = wx.Button(self.panel_1, wx.ID_ANY, u"Сохранить")
        sizer_1.Add(self.button_SAVE, 0, 0, 0)

        sizer_1.Realize()

        grid_sizer_1.AddGrowableCol(2)

        sizer_4.AddGrowableRow(0)
        self.panel_1.SetSizer(sizer_4)

        self.Layout()
        self.Centre()


class Ui_DischargeMesurement_Inspect(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_4 = wx.WrapSizer(wx.VERTICAL)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Основное"), wx.VERTICAL)
        sizer_4.Add(sizer_3, 1, wx.EXPAND | wx.RIGHT | wx.TOP, 20)

        grid_sizer_3 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_3.Add(grid_sizer_3, 1, wx.RIGHT, 20)

        label_14 = wx.StaticText(self, wx.ID_ANY, "ID:")
        grid_sizer_3.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self, wx.ID_ANY, "")
        self.field_RID.Wrap(40)
        grid_sizer_3.Add(self.field_RID, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        label_15 = wx.StaticText(self, wx.ID_ANY, u"Серия:")
        grid_sizer_3.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DSID = wx.StaticText(self, wx.ID_ANY, "")
        self.field_DSID.Wrap(40)
        grid_sizer_3.Add(self.field_DSID, 0, wx.EXPAND, 0)

        label_16 = wx.StaticText(self, wx.ID_ANY, u"Замер №:")
        grid_sizer_3.Add(label_16, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_SNumber = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_3.Add(self.field_SNumber, 0, 0, 0)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Керн"), wx.HORIZONTAL)
        sizer_4.Add(sizer_2, 1, wx.RIGHT | wx.TOP, 20)

        grid_sizer_1 = wx.FlexGridSizer(6, 2, 5, 5)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND | wx.RIGHT, 20)

        label_7 = wx.StaticText(self, wx.ID_ANY, u"Рег. № разгрузка:")
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DschNumber = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_DschNumber, 0, 0, 0)

        label_8 = wx.StaticText(self, wx.ID_ANY, u"Рег. № образец керна:")
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreNumber = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_CoreNumber, 0, 0, 0)

        label_9 = wx.StaticText(self, wx.ID_ANY, u"Диаметр образца керна:")
        grid_sizer_1.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Diameter = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Diameter, 0, 0, 0)

        label_10 = wx.StaticText(self, wx.ID_ANY, u"Длина образца керна:")
        grid_sizer_1.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Length_ = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Length_, 0, 0, 0)

        label_13 = wx.StaticText(self, wx.ID_ANY, u"Вес образца керна:")
        grid_sizer_1.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Weight = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Weight, 0, 0, 0)

        label_21 = wx.StaticText(self, wx.ID_ANY, u"Глубина взятия керна:")
        grid_sizer_1.Add(label_21, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreDepth = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_CoreDepth, 0, 0, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Тензодатчики"), wx.HORIZONTAL)
        sizer_4.Add(sizer_1, 1, wx.RIGHT | wx.TOP, 20)

        grid_sizer_2 = wx.FlexGridSizer(5, 2, 5, 5)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Тензопатрон №:")
        grid_sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CartNumber = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_CartNumber, 0, wx.EXPAND, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, u"Партия тензодатчиков №:")
        grid_sizer_2.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PartNumber = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_PartNumber, 0, 0, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, u"Сопротивление тензорезистора:")
        grid_sizer_2.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_R = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_R, 0, 0, 0)

        label_11 = wx.StaticText(self, wx.ID_ANY, u"Сопр. компенсат. тензорезистора:")
        grid_sizer_2.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RComp = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_RComp, 0, 0, 0)

        label_12 = wx.StaticText(self, wx.ID_ANY, u"Коэф. чувств. тензодатчиков:")
        grid_sizer_2.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Sensitivity = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_Sensitivity, 0, 0, 0)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Тензометрия"), wx.HORIZONTAL)
        sizer_4.Add(sizer_5, 1, wx.EXPAND | wx.RIGHT | wx.TOP, 20)

        grid_sizer_4 = wx.FlexGridSizer(6, 2, 5, 5)
        sizer_5.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"t прохождения продольных волн (ультразвуковое профлилрование и др.):", style=wx.ALIGN_RIGHT)
        label_3.Wrap(300)
        grid_sizer_4.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_TP_1 = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_1, 0, wx.EXPAND, 0)

        label_17 = wx.StaticText(self, wx.ID_ANY, u"t прохождения продольных волн (между торцами и др.):", style=wx.ALIGN_RIGHT)
        label_17.Wrap(300)
        grid_sizer_4.Add(label_17, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_TP_2 = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_2, 0, 0, 0)

        label_18 = wx.StaticText(self, wx.ID_ANY, u"t прохождения поверхностных волн:", style=wx.ALIGN_RIGHT)
        label_18.Wrap(300)
        grid_sizer_4.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_TR = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TR, 0, 0, 0)

        label_19 = wx.StaticText(self, wx.ID_ANY, u"t прохождения поперечных волн:", style=wx.ALIGN_RIGHT)
        grid_sizer_4.Add(label_19, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_TS = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TS, 0, 0, 0)

        label_20 = wx.StaticText(self, wx.ID_ANY, u"Статич. коэф. Пуассона:", style=wx.ALIGN_RIGHT)
        label_20.Wrap(300)
        grid_sizer_4.Add(label_20, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PuassonStatic = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_PuassonStatic, 0, 0, 0)

        label_22 = wx.StaticText(self, wx.ID_ANY, u"Статич. модуль Юнга:", style=wx.ALIGN_RIGHT)
        grid_sizer_4.Add(label_22, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_YungStatic = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_YungStatic, 0, 0, 0)

        sizer_4.Add((0, 0), 0, 0, 0)

        sizer_4.Add((0, 0), 0, 0, 0)

        sizer_4.Add((0, 0), 0, 0, 0)

        sizer_4.Add((0, 0), 0, 0, 0)

        grid_sizer_4.AddGrowableCol(1)

        grid_sizer_2.AddGrowableCol(1)

        grid_sizer_1.AddGrowableCol(1)

        grid_sizer_3.AddGrowableCol(1)

        self.SetSizer(sizer_4)
        sizer_4.Fit(self)

        self.Layout()


class Ui_DischargeMeasurement_Filter(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((387, 472))
        self.SetTitle(u"Фильтр")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.FlexGridSizer(5, 2, 5, 10)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 10)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Серия:")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        self.field_DSID_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_3.Add(self.field_DSID_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_DSID = wx.Choice(self, wx.ID_ANY, choices=[])
        self.field_DSID.Enable(False)
        sizer_3.Add(self.field_DSID, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Порядковый номер:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sizer_8 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)

        self.field_SNumber_min_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_8.Add(self.field_SNumber_min_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_SNumber_min = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=100)
        self.field_SNumber_min.Enable(False)
        sizer_8.Add(self.field_SNumber_min, 0, 0, 0)

        label_11 = wx.StaticText(self, wx.ID_ANY, " - ")
        sizer_8.Add(label_11, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 5)

        self.field_SNumber_max_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_8.Add(self.field_SNumber_max_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_SNumber_max = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=100)
        self.field_SNumber_max.Enable(False)
        sizer_8.Add(self.field_SNumber_max, 0, 0, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, u"Диаметр образца:")
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sizer_7 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)

        self.field_Diameter_min_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_7.Add(self.field_Diameter_min_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Diameter_min = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Diameter_min.Enable(False)
        self.field_Diameter_min.SetDigits(2)
        sizer_7.Add(self.field_Diameter_min, 0, wx.EXPAND, 0)

        label_10 = wx.StaticText(self, wx.ID_ANY, " - ")
        sizer_7.Add(label_10, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 5)

        self.field_Diameter_max_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_7.Add(self.field_Diameter_max_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Diameter_max = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Diameter_max.Enable(False)
        self.field_Diameter_max.SetDigits(2)
        sizer_7.Add(self.field_Diameter_max, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, u"Длина образца:")
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sizer_5 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        self.field_Length_min_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_5.Add(self.field_Length_min_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Length_min = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Length_min.Enable(False)
        self.field_Length_min.SetDigits(2)
        sizer_5.Add(self.field_Length_min, 0, wx.EXPAND, 0)

        label_7 = wx.StaticText(self, wx.ID_ANY, " - ")
        sizer_5.Add(label_7, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 5)

        self.field_Length_max_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_5.Add(self.field_Length_max_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Length_max = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Length_max.Enable(False)
        self.field_Length_max.SetDigits(2)
        sizer_5.Add(self.field_Length_max, 0, wx.EXPAND, 0)

        label_8 = wx.StaticText(self, wx.ID_ANY, u"Вес образца:")
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sizer_6 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)

        self.field_Weight_min_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_6.Add(self.field_Weight_min_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Weight_min = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Weight_min.Enable(False)
        self.field_Weight_min.SetDigits(2)
        sizer_6.Add(self.field_Weight_min, 0, wx.EXPAND, 0)

        label_9 = wx.StaticText(self, wx.ID_ANY, " - ")
        sizer_6.Add(label_9, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 5)

        self.field_Weight_max_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        sizer_6.Add(self.field_Weight_max_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Weight_max = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Weight_max.Enable(False)
        self.field_Weight_max.SetDigits(2)
        sizer_6.Add(self.field_Weight_max, 0, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        sizer_6.AddGrowableCol(2)
        sizer_6.AddGrowableCol(5)

        sizer_5.AddGrowableCol(2)
        sizer_5.AddGrowableCol(5)

        sizer_7.AddGrowableCol(2)
        sizer_7.AddGrowableCol(5)

        sizer_8.AddGrowableCol(2)
        sizer_8.AddGrowableCol(5)

        sizer_3.AddGrowableCol(1)

        grid_sizer_1.AddGrowableCol(1)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.Centre()


class Ui_BoreHoles_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((797, 425))
        self.SetTitle(u"Список скважин")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.list_container = wx.BoxSizer(wx.VERTICAL)

        self.list = widgets.table_view.TableView(self.panel_1, wx.ID_ANY)
        self.list_container.Add(self.list, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.list_container)

        self.Layout()
        self.Centre()


class Ui_OrigSampleSets_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((797, 425))
        self.SetTitle(u"Список оригинальных наборов образцов")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.list_container = wx.BoxSizer(wx.VERTICAL)

        self.list = widgets.table_view.TableView(self.panel_1, wx.ID_ANY)
        self.list_container.Add(self.list, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.list_container)

        self.Layout()
        self.Centre()


class Ui_OrigSampleSets_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((432, 609))
        self.SetTitle(u"Создание/Редактирование \"Набор образцов\"")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.main = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.main.SetMinSize((451, 556))
        self.notebook_1.AddPage(self.main, u"Основное")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_1 = wx.ScrolledWindow(self.main, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_1.SetScrollRate(10, 10)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 10)

        sizer_4 = wx.WrapSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_41 = wx.StaticText(self.panel_1, wx.ID_ANY, "ID:")
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.panel_1, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, (0, 2), (1, 1), wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Рег. №")
        grid_sizer_1.Add(label_1, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Number = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_Number.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Number, (1, 2), (1, 1), wx.EXPAND, 0)

        label_42 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Название:")
        label_42.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_42, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_Name.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Name, (2, 2), (1, 1), wx.EXPAND, 0)

        label_43 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Комментарий:")
        label_43.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_43, (3, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, (3, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.SetMinSize((200, 46))
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, (3, 2), (1, 1), wx.EXPAND, 0)

        label_44 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Тип материала:")
        label_44.SetToolTip(u"Внутренний идентификатор замера")
        label_44.Wrap(150)
        grid_sizer_1.Add(label_44, (4, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_SampleType = wx.Choice(self.panel_1, wx.ID_ANY, choices=[u"Керн", u"Штуф", u"Дисперсный материал"])
        self.field_SampleType.SetSelection(0)
        grid_sizer_1.Add(self.field_SampleType, (4, 2), (1, 1), wx.EXPAND, 0)

        sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Координаты точки отбора образцов"), wx.HORIZONTAL)
        sizer_4.Add(sizer_12, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_11 = wx.FlexGridSizer(2, 3, 5, 5)
        sizer_12.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "X")
        label_20.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 1")
        grid_sizer_11.Add(label_20, 0, wx.ALIGN_BOTTOM, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Y")
        label_21.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 2")
        grid_sizer_11.Add(label_21, 0, wx.ALIGN_BOTTOM, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Z")
        label_22.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 1")
        grid_sizer_11.Add(label_22, 0, wx.ALIGN_BOTTOM, 0)

        self.field_X = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=-1000000.0, max=1000000.0)
        self.field_X.SetDigits(2)
        grid_sizer_11.Add(self.field_X, 0, wx.EXPAND, 0)

        self.field_Y = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=-1000000.0, max=1000000.0)
        self.field_Y.SetDigits(2)
        grid_sizer_11.Add(self.field_Y, 0, wx.EXPAND, 0)

        self.field_Z = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=-1000000.0, max=1000000.0)
        self.field_Z.SetDigits(2)
        grid_sizer_11.Add(self.field_Z, 0, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_2, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_45 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Горный обьект:")
        label_45.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_2.Add(label_45, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_MOID = widgets.relation_selector.RelationSelector(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.field_MOID, (0, 2), (1, 1), wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Скважина:")
        grid_sizer_2.Add(label_2, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_HID = widgets.relation_selector.RelationSelector(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.field_HID, (1, 2), (1, 1), wx.EXPAND, 0)

        label_46 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Дата отбора:")
        label_46.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_2.Add(label_46, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_SetDate = wx.adv.DatePickerCtrl(self.panel_1, wx.ID_ANY, style=wx.adv.DP_DEFAULT | wx.adv.DP_DROPDOWN | wx.adv.DP_SHOWCENTURY | wx.adv.DP_SPIN)
        grid_sizer_2.Add(self.field_SetDate, (2, 2), (1, 1), wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self.main, wx.ID_SAVE, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_2.AddButton(self.button_SAVE)

        self.button_CANCEL = wx.Button(self.main, wx.ID_CANCEL, u"Отмена")
        sizer_2.AddButton(self.button_CANCEL)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"Сопутствующие материалы")

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)

        self.supplied_data = widgets.supplied_data_editor.SuppliedDataEditor(self.notebook_1_pane_2, wx.ID_ANY)
        sizer_3.Add(self.supplied_data, 1, wx.EXPAND, 0)

        self.notebook_1_pane_2.SetSizer(sizer_3)

        sizer_2.Realize()

        grid_sizer_2.AddGrowableCol(2)

        grid_sizer_11.AddGrowableCol(0)
        grid_sizer_11.AddGrowableCol(1)
        grid_sizer_11.AddGrowableCol(2)

        grid_sizer_1.AddGrowableCol(2)

        self.panel_1.SetSizer(sizer_4)

        self.main.SetSizer(sizer_1)

        self.Layout()
        self.Centre()


class Ui_Settings(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle(u"Настройки")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, u"База данных")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.btn_edit_database_access = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, u"Редактировать доступы к базе данных")
        sizer_3.Add(self.btn_edit_database_access, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self, wx.ID_ANY, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_2.Add(self.button_SAVE, 0, 0, 0)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.notebook_1_pane_1.SetSizer(sizer_3)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_SAVE.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.Centre()


class Ui_Stations_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((983, 565))
        self.SetTitle(u"Список станций")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.list_container = wx.BoxSizer(wx.VERTICAL)

        self.list = widgets.table_view.TableView(self.panel_1, wx.ID_ANY)
        self.list_container.Add(self.list, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.list_container)

        self.Layout()
        self.Centre()


class Ui_MineObjects_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((349, 467))
        self.SetTitle(u"Список горных объектов")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.tree_container = wx.BoxSizer(wx.VERTICAL)

        self.tree = widgets.tree_view.TreeView(self.panel_1, wx.ID_ANY)
        self.tree_container.Add(self.tree, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.tree_container)

        self.Layout()
        self.Centre()


class Ui_CoordSystems_List(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((314, 469))
        self.SetTitle(u"Список систем координат")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.tree_container = wx.BoxSizer(wx.VERTICAL)

        self.tree = widgets.tree_view.TreeView(self.panel_1, wx.ID_ANY)
        self.tree_container.Add(self.tree, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.tree_container)

        self.Layout()
        self.Centre()


class Ui_Stations_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((472, 620))
        self.SetTitle(u"Редактировать/Создать станцию")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.main = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.main.SetMinSize((451, 556))
        self.notebook_1.AddPage(self.main, u"Основное")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.ScrolledWindow(self.main, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_2.SetScrollRate(10, 10)
        sizer_2.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 10)

        sizer_4 = wx.WrapSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_41 = wx.StaticText(self.panel_2, wx.ID_ANY, "ID:")
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.panel_2, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, (0, 2), (1, 1), wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Рег. №")
        grid_sizer_1.Add(label_1, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Number = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        self.field_Number.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Number, (1, 2), (1, 1), wx.EXPAND, 0)

        label_42 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Название:")
        label_42.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_42, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Name = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        self.field_Name.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Name, (2, 2), (1, 1), wx.EXPAND, 0)

        label_43 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Комментарий:")
        label_43.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_43, (3, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, (3, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self.panel_2, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.SetMinSize((200, 46))
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, (3, 2), (1, 1), wx.EXPAND, 0)

        label_44 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Горный объект:")
        label_44.SetToolTip(u"Внутренний идентификатор замера")
        label_44.Wrap(150)
        grid_sizer_1.Add(label_44, (4, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_MOID = widgets.relation_selector.RelationSelector(self.panel_2, wx.ID_ANY)
        grid_sizer_1.Add(self.field_MOID, (4, 2), (1, 1), wx.EXPAND, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self.panel_2, wx.ID_ANY, u"Позиция станции"), wx.VERTICAL)
        sizer_4.Add(sizer_1, 0, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_2 = wx.FlexGridSizer(2, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_2, wx.ID_ANY, "X")
        grid_sizer_2.Add(label_2, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_2, wx.ID_ANY, "Y")
        grid_sizer_2.Add(label_4, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_2, wx.ID_ANY, "Z")
        grid_sizer_2.Add(label_5, 0, 0, 0)

        self.field_X = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_X.SetDigits(2)
        grid_sizer_2.Add(self.field_X, 0, 0, 0)

        self.field_Y = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Y.SetDigits(2)
        grid_sizer_2.Add(self.field_Y, 0, 0, 0)

        self.field_Z = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Z.SetDigits(2)
        grid_sizer_2.Add(self.field_Z, 0, 0, 0)

        grid_sizer_3 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_3, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_52 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Количество скважин:")
        label_52.SetToolTip(u"Внутренний идентификатор замера")
        label_52.Wrap(150)
        grid_sizer_3.Add(label_52, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_HoleCount = wx.SpinCtrl(self.panel_2, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.field_HoleCount, (0, 2), (1, 1), 0, 0)

        label_50 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Дата закладки станции / начала измерений:")
        label_50.SetToolTip(u"Внутренний идентификатор замера")
        label_50.Wrap(150)
        grid_sizer_3.Add(label_50, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_StartDate = wx.adv.DatePickerCtrl(self.panel_2, wx.ID_ANY)
        grid_sizer_3.Add(self.field_StartDate, (1, 2), (1, 1), 0, 0)

        label_51 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Дата завершения измерений:")
        label_51.SetToolTip(u"Внутренний идентификатор замера")
        label_51.Wrap(150)
        grid_sizer_3.Add(label_51, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_EndDate_enabled = wx.CheckBox(self.panel_2, wx.ID_ANY, "")
        grid_sizer_3.Add(self.field_EndDate_enabled, (2, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_EndDate = wx.adv.DatePickerCtrl(self.panel_2, wx.ID_ANY)
        self.field_EndDate.Enable(False)
        grid_sizer_3.Add(self.field_EndDate, (2, 2), (1, 1), 0, 0)

        sizer_5 = wx.StdDialogButtonSizer()
        sizer_2.Add(sizer_5, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self.main, wx.ID_SAVE, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_5.AddButton(self.button_SAVE)

        self.button_CANCEL = wx.Button(self.main, wx.ID_CANCEL, u"Отмена")
        sizer_5.AddButton(self.button_CANCEL)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"Сопутствующие материалы")

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)

        self.supplied_data = widgets.supplied_data_editor.SuppliedDataEditor(self.notebook_1_pane_2, wx.ID_ANY)
        sizer_3.Add(self.supplied_data, 1, wx.EXPAND, 0)

        self.notebook_1_pane_2.SetSizer(sizer_3)

        sizer_5.Realize()

        grid_sizer_3.AddGrowableCol(2)

        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_2.AddGrowableCol(1)
        grid_sizer_2.AddGrowableCol(2)

        grid_sizer_1.AddGrowableCol(2)

        self.panel_2.SetSizer(sizer_4)

        self.main.SetSizer(sizer_2)

        self.Layout()


class Ui_MineObjects_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((430, 553))
        self.SetTitle(u"Редактировать/Создать горный объект")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.main = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.main.SetMinSize((451, 556))
        self.notebook_1.AddPage(self.main, u"Основное")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.ScrolledWindow(self.main, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_2.SetScrollRate(10, 10)
        sizer_2.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 10)

        sizer_4 = wx.WrapSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND, 20)

        label_41 = wx.StaticText(self.panel_2, wx.ID_ANY, "ID:")
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.panel_2, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, (0, 2), (1, 1), wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Родительский объект:")
        label_1.Wrap(120)
        grid_sizer_1.Add(label_1, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PID_enabled = wx.CheckBox(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_PID_enabled, (1, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_PID = widgets.relation_selector.RelationSelector(self.panel_2, wx.ID_ANY)
        self.field_PID.Enable(False)
        grid_sizer_1.Add(self.field_PID, (1, 2), (1, 1), wx.EXPAND, 0)

        label_42 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Название:")
        label_42.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_42, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Name = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        self.field_Name.SetMinSize((200, 23))
        grid_sizer_1.Add(self.field_Name, (2, 2), (1, 1), wx.EXPAND, 0)

        label_43 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Комментарий:")
        label_43.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_43, (3, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, (3, 1), (1, 1), wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self.panel_2, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.SetMinSize((200, 46))
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, (3, 2), (1, 1), wx.EXPAND, 0)

        label_44 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Тип объекта:")
        label_44.SetToolTip(u"Внутренний идентификатор замера")
        label_44.Wrap(150)
        grid_sizer_1.Add(label_44, (4, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Type = wx.Choice(self.panel_2, wx.ID_ANY, choices=[u"Регион", u"Горный массив", u"Месторождение", u"Горизонт", u"Выработка"])
        self.field_Type.SetSelection(0)
        grid_sizer_1.Add(self.field_Type, (4, 2), (1, 1), wx.EXPAND | wx.RIGHT, 5)

        label_2 = wx.StaticText(self.panel_2, wx.ID_ANY, u"Система координат")
        label_2.Wrap(100)
        grid_sizer_1.Add(label_2, (5, 0), (1, 1), wx.ALIGN_RIGHT, 0)

        self.field_CSID = widgets.relation_selector.RelationSelector(self.panel_2, wx.ID_ANY)
        grid_sizer_1.Add(self.field_CSID, (5, 2), (1, 1), wx.EXPAND, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self.panel_2, wx.ID_ANY, u"Ограничения координат"), wx.HORIZONTAL)
        sizer_4.Add(sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 4, 5, 5)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        label_7 = wx.StaticText(self.panel_2, wx.ID_ANY, "X")
        grid_sizer_2.Add(label_7, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_2, wx.ID_ANY, "Y")
        grid_sizer_2.Add(label_8, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_2, wx.ID_ANY, "Z")
        grid_sizer_2.Add(label_9, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_2, wx.ID_ANY, "Min")
        grid_sizer_2.Add(label_5, 0, 0, 0)

        self.spin_ctrl_double_1 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_1.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_1, 0, 0, 0)

        self.spin_ctrl_double_2 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_2.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_2, 0, 0, 0)

        self.spin_ctrl_double_3 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_3.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_3, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_2, wx.ID_ANY, "Max")
        grid_sizer_2.Add(label_6, 0, 0, 0)

        self.spin_ctrl_double_4 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_4.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_4, 0, 0, 0)

        self.spin_ctrl_double_5 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_5.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_5, 0, 0, 0)

        self.spin_ctrl_double_6 = wx.SpinCtrlDouble(self.panel_2, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.spin_ctrl_double_6.SetDigits(2)
        grid_sizer_2.Add(self.spin_ctrl_double_6, 0, 0, 0)

        sizer_5 = wx.StdDialogButtonSizer()
        sizer_2.Add(sizer_5, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self.main, wx.ID_SAVE, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_5.AddButton(self.button_SAVE)

        self.button_CANCEL = wx.Button(self.main, wx.ID_CANCEL, u"Отмена")
        sizer_5.AddButton(self.button_CANCEL)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"Сопутствующие материалы")

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)

        self.supplied_data = widgets.supplied_data_editor.SuppliedDataEditor(self.notebook_1_pane_2, wx.ID_ANY)
        sizer_3.Add(self.supplied_data, 1, wx.EXPAND, 0)

        self.notebook_1_pane_2.SetSizer(sizer_3)

        sizer_5.Realize()

        grid_sizer_2.AddGrowableCol(1)
        grid_sizer_2.AddGrowableCol(2)
        grid_sizer_2.AddGrowableCol(3)

        grid_sizer_1.AddGrowableCol(2)

        self.panel_2.SetSizer(sizer_4)

        self.main.SetSizer(sizer_2)

        self.Layout()


class Ui_Inspect(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 491))
        self.SetTitle("frame_3")

        # Menu Bar
        self.frame_3_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_3_menubar.Append(wxglade_tmp_menu, u"Экспортировать")
        self.SetMenuBar(self.frame_3_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.window_1 = wx.SplitterWindow(self.panel_1, wx.ID_ANY, style=wx.SP_3D | wx.SP_LIVE_UPDATE)
        self.window_1.SetMinimumPaneSize(20)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)

        self.panel_2 = wx.ScrolledWindow(self.window_1, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_2.SetScrollRate(10, 10)

        self.grid = wx.FlexGridSizer(0, 2, 0, 0)

        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, u"Сопутствующие материалы"), wx.VERTICAL)

        self.supplied_data = widgets.supplied_data_viewer.SuppliedData_Viewer(self.window_1_pane_2, wx.ID_ANY)
        sizer_3.Add(self.supplied_data, 1, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self.panel_1, wx.ID_ANY, u"ОК")
        self.button_OK.SetDefault()
        sizer_2.Add(self.button_OK, 0, 0, 0)

        sizer_2.Realize()

        self.window_1_pane_2.SetSizer(sizer_3)

        self.panel_2.SetSizer(self.grid)

        self.window_1.SplitHorizontally(self.panel_2, self.window_1_pane_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()


class MyDialog(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.button_1 = wx.Button(self, wx.ID_ANY, "button_1", style=wx.BORDER_NONE | wx.BU_EXACTFIT)
        self.button_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 1, ""))
        self.Layout()


class UI_ExportWizard(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((421, 514))
        self.SetTitle(u"Мастер экспорта таблиц")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.FlexGridSizer(4, 1, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 5)

        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_2.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND, 5)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Экспортировать как:")
        grid_sizer_1.Add(label_1, 0, 0, 0)

        self.field_export_type = wx.Choice(self.panel_1, wx.ID_ANY, choices=["CSV", "XLS"])
        self.field_export_type.SetSelection(0)
        grid_sizer_1.Add(self.field_export_type, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Файл:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_RIGHT, 0)

        sizer_6 = wx.FlexGridSizer(1, 2, 0, 5)
        grid_sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)

        self.field_file_name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_6.Add(self.field_file_name, 0, wx.EXPAND, 0)

        self.btn_SelectFile = wx.Button(self.panel_1, wx.ID_ANY, u"…")
        self.btn_SelectFile.SetMinSize((30, 20))
        sizer_6.Add(self.btn_SelectFile, 0, wx.ALIGN_CENTER, 0)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Столбцы"), wx.VERTICAL)
        sizer_2.Add(sizer_5, 1, wx.BOTTOM | wx.EXPAND, 5)

        self.btn_select_all_cols = wx.Button(self.panel_1, wx.ID_ANY, u"Выбрать все")
        sizer_5.Add(self.btn_select_all_cols, 0, wx.ALIGN_RIGHT, 0)

        self.columns = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=[])
        self.columns.SetMinSize((384, 130))
        sizer_5.Add(self.columns, 0, wx.EXPAND, 0)

        self.table = wx.ListCtrl(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        sizer_2.Add(self.table, 1, wx.BOTTOM | wx.EXPAND, 5)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Экспортирование"), wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 5)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.export_progress = wx.Gauge(self.panel_1, wx.ID_ANY, 10)
        grid_sizer_2.Add(self.export_progress, 0, wx.EXPAND, 0)

        self.btn_export = wx.Button(self.panel_1, wx.ID_ANY, u"Экспортировать")
        grid_sizer_2.Add(self.btn_export, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(0)

        sizer_6.AddGrowableCol(0)

        grid_sizer_1.AddGrowableCol(1)

        sizer_2.AddGrowableRow(1)
        sizer_2.AddGrowableRow(2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()


class Ui_DatabaseAccess(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(u"Доступ к базе данных")

        sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)

        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 25)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Логин:")
        grid_sizer_1.Add(label_1, 0, 0, 0)

        self.field_login = wx.TextCtrl(self, wx.ID_ANY, "")
        self.field_login.SetMinSize((250, 23))
        grid_sizer_1.Add(self.field_login, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Пароль:")
        grid_sizer_1.Add(label_2, 0, 0, 0)

        self.field_password = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.field_password.SetMinSize((250, 23))
        grid_sizer_1.Add(self.field_password, 0, wx.EXPAND, 0)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Расширеные настройки"), wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_3.Add(grid_sizer_2, 1, wx.ALL | wx.EXPAND, 5)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"IP сервера БД:")
        grid_sizer_2.Add(label_3, 0, 0, 0)

        self.field_ip = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_ip, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, u"Порт сервера:")
        grid_sizer_2.Add(label_4, 0, 0, 0)

        self.field_port = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=65535)
        grid_sizer_2.Add(self.field_port, 0, 0, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, u"Название БД:")
        grid_sizer_2.Add(label_5, 0, 0, 0)

        self.field_name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_2.Add(self.field_name, 0, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self, wx.ID_SAVE, "")
        self.button_SAVE.SetDefault()
        sizer_2.AddButton(self.button_SAVE)

        sizer_2.Realize()

        grid_sizer_2.AddGrowableCol(1)

        grid_sizer_1.AddGrowableCol(1)

        sizer_1.AddGrowableRow(2)
        sizer_1.AddGrowableCol(0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_SAVE.GetId())

        self.Layout()
        self.Centre()


class App(wx.App):
    def OnInit(self):
        self.MainWindow = Ui_MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MainWindow)
        self.MainWindow.Show()
        return True

if __name__ == "__main__":
    app = App(0)
    app.MainLoop()
