# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Nov  9 05:02:56 2023
#

import wx
# begin wxGlade: dependencies
import wx.adv
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ui_DischargeSeries_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ui_DischargeSeries_Editor.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((331, 609))
        self.SetTitle(u"Создание/Редактирование \"Набор замеров\"")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.main = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.main.SetMinSize((451, 556))
        self.notebook_1.AddPage(self.main, u"Основное")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_1 = wx.ScrolledWindow(self.main, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_1.SetScrollRate(10, 10)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 10)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridBagSizer(10, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_41 = wx.StaticText(self.panel_1, wx.ID_ANY, "ID:")
        label_41.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        field_RID = wx.StaticText(self.panel_1, wx.ID_ANY, "0")
        grid_sizer_1.Add(field_RID, (0, 1), (1, 1), wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Рег. №")
        label_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_1, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_1.SetMinSize((200, 23))
        grid_sizer_1.Add(self.text_ctrl_1, (1, 1), (1, 1), 0, 0)

        label_42 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Название:")
        label_42.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_42.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_42, (2, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_2.SetMinSize((200, 23))
        grid_sizer_1.Add(self.text_ctrl_2, (2, 1), (1, 1), 0, 0)

        label_43 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Комментарий:")
        label_43.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_43.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_43, (3, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.text_ctrl_3.SetMinSize((200, 46))
        grid_sizer_1.Add(self.text_ctrl_3, (3, 1), (1, 1), 0, 0)

        label_44 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Исходный набор образцов:")
        label_44.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_44.SetToolTip(u"Внутренний идентификатор замера")
        label_44.Wrap(150)
        grid_sizer_1.Add(label_44, (4, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.combo_box_1 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_1.Add(self.combo_box_1, (4, 1), (1, 1), 0, 0)

        label_45 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Исходный набор образцов:")
        label_45.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_45.SetToolTip(u"Внутренний идентификатор замера")
        label_45.Wrap(150)
        grid_sizer_1.Add(label_45, (5, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.calendar_ctrl_1 = wx.adv.CalendarCtrl(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.calendar_ctrl_1, (5, 1), (1, 1), 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self.main, wx.ID_SAVE, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_2.AddButton(self.button_SAVE)

        self.button_CANCEL = wx.Button(self.main, wx.ID_CANCEL, u"Отмена")
        sizer_2.AddButton(self.button_CANCEL)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"Сопутствующие материалы")

        sizer_2.Realize()

        self.panel_1.SetSizer(sizer_4)

        self.main.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class Ui_DischargeSeries_Editor
