# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Nov  9 05:02:56 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ui_DischargeMeasurement_Editor(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ui_DischargeMeasurement_Editor.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((432, 609))
        self.SetTitle(u"Создание/Редактирование \"Поразгрузочный замер\"")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.main = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.main.SetMinSize((451, 556))
        self.notebook_1.AddPage(self.main, u"Основное")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_1 = wx.ScrolledWindow(self.main, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_1.SetScrollRate(10, 10)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 10)

        sizer_4 = wx.WrapSizer(wx.VERTICAL)

        grid_sizer_1 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_4.Add(grid_sizer_1, 1, wx.BOTTOM | wx.TOP, 10)

        label_41 = wx.StaticText(self.panel_1, wx.ID_ANY, "ID:")
        label_41.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_41.SetToolTip(u"Внутренний идентификатор замера")
        grid_sizer_1.Add(label_41, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RID = wx.StaticText(self.panel_1, wx.ID_ANY, "0")
        grid_sizer_1.Add(self.field_RID, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_42 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Серия:")
        label_42.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_42.SetToolTip(u"Привязка к серии замеров")
        grid_sizer_1.Add(label_42, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DSID = wx.Choice(self.panel_1, wx.ID_ANY, choices=[u"-- не выбрано --"])
        self.field_DSID.SetMinSize((320, 20))
        self.field_DSID.SetSelection(0)
        grid_sizer_1.Add(self.field_DSID, 0, wx.EXPAND, 0)

        label_43 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Замер №:")
        label_43.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_43.SetToolTip(u"Порядковый номер замера.")
        grid_sizer_1.Add(label_43, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_SNumber = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "", min=1, max=1000000000)
        grid_sizer_1.Add(self.field_SNumber, 0, 0, 0)

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Образец керна"), wx.HORIZONTAL)
        sizer_4.Add(sizer_9, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_10 = wx.FlexGridSizer(6, 2, 5, 5)
        sizer_9.Add(grid_sizer_10, 1, wx.BOTTOM | wx.TOP, 10)

        label_44 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Рег. № разгрузки:")
        label_44.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_44.SetToolTip(u"Регистрационный номер разгрузки")
        grid_sizer_10.Add(label_44, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DschNumber = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_DschNumber.SetMinSize((200, 23))
        grid_sizer_10.Add(self.field_DschNumber, 0, 0, 0)

        label_60 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Рег. № керна:")
        label_60.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_60.SetToolTip(u"Регистрационный номер образца керна")
        grid_sizer_10.Add(label_60, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreNumber = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_CoreNumber.SetMinSize((200, 23))
        grid_sizer_10.Add(self.field_CoreNumber, 0, 0, 0)

        label_61 = wx.StaticText(self.panel_1, wx.ID_ANY, u"⌀ керна, мм:")
        label_61.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_61.SetToolTip(u"Диаметр образца керна")
        grid_sizer_10.Add(label_61, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Diameter = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Diameter.SetDigits(2)
        grid_sizer_10.Add(self.field_Diameter, 0, 0, 0)

        label_64 = wx.StaticText(self.panel_1, wx.ID_ANY, u"L образца керна, мм:")
        label_64.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_64.SetToolTip(u"Длина образца керна")
        grid_sizer_10.Add(label_64, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Length = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Length.SetDigits(2)
        grid_sizer_10.Add(self.field_Length, 0, 0, 0)

        label_65 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Вес керна, г:")
        label_65.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_65.SetToolTip(u"Вес образца керна")
        grid_sizer_10.Add(label_65, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Weight = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Weight.SetDigits(2)
        grid_sizer_10.Add(self.field_Weight, 0, 0, 0)

        label_66 = wx.StaticText(self.panel_1, wx.ID_ANY, u"H взятия образца керна, м:")
        label_66.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_66.SetToolTip(u"Глубина взятия образца керна, м")
        grid_sizer_10.Add(label_66, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CoreDepth = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_CoreDepth.SetDigits(2)
        grid_sizer_10.Add(self.field_CoreDepth, 0, 0, 0)

        sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Параметры тензодатчиков"), wx.VERTICAL)
        sizer_4.Add(sizer_11, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_12 = wx.GridBagSizer(5, 5)
        sizer_11.Add(grid_sizer_12, 1, wx.BOTTOM | wx.TOP, 10)

        label_57 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Тензопатрон №:")
        label_57.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_57.SetToolTip(u"Номер партии тензодатчиков")
        grid_sizer_12.Add(label_57, (0, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_CartNumber = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_CartNumber.SetMinSize((200, 23))
        grid_sizer_12.Add(self.field_CartNumber, (0, 1), (1, 1), 0, 0)

        label_58 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Партия тензодатчиков №:")
        label_58.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_58.SetToolTip(u"Номер партии тензодатчиков")
        grid_sizer_12.Add(label_58, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PartNumber = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_PartNumber.SetMinSize((200, 23))
        grid_sizer_12.Add(self.field_PartNumber, (1, 1), (1, 1), 0, 0)

        sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Сопротивление тензорезистора, Ом"), wx.HORIZONTAL)
        sizer_11.Add(sizer_12, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_11 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_12.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_20.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_20.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 1")
        grid_sizer_11.Add(label_20, 0, wx.ALIGN_BOTTOM, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_21.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_21.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 2")
        grid_sizer_11.Add(label_21, 0, wx.ALIGN_BOTTOM, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "3")
        label_22.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_22.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 1")
        grid_sizer_11.Add(label_22, 0, wx.ALIGN_BOTTOM, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "4")
        label_23.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_23.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 2")
        grid_sizer_11.Add(label_23, 0, wx.ALIGN_BOTTOM, 0)

        self.field_R1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_R1.SetDigits(2)
        grid_sizer_11.Add(self.field_R1, 0, wx.EXPAND, 0)

        self.field_R2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_R2.SetDigits(2)
        grid_sizer_11.Add(self.field_R2, 0, wx.EXPAND, 0)

        self.field_R3 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_R3.SetDigits(2)
        grid_sizer_11.Add(self.field_R3, 0, wx.EXPAND, 0)

        self.field_R4 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_R4.SetDigits(2)
        grid_sizer_11.Add(self.field_R4, 0, wx.EXPAND, 0)

        grid_sizer_14 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_11.Add(grid_sizer_14, 1, 0, 0)

        label_212 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Ω компенсаторного резистора, Ом:")
        label_212.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_212.SetToolTip(u"Сопротивление компенсационного резистора")
        grid_sizer_14.Add(label_212, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_RComp = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_RComp.SetDigits(2)
        grid_sizer_14.Add(self.field_RComp, 0, 0, 0)

        label_213 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Коэф. чувств. тензодатчиков:")
        label_213.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_213.SetToolTip(u"Коэффициент чувствительности тензодатчиков")
        grid_sizer_14.Add(label_213, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Sensitivity = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100000.0)
        self.field_Sensitivity.SetDigits(2)
        grid_sizer_14.Add(self.field_Sensitivity, 0, 0, 0)

        sizer_10 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Тензометрия"), wx.VERTICAL)
        sizer_4.Add(sizer_10, 1, wx.BOTTOM | wx.EXPAND, 10)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"t прохождения продольных волн (ультразв. проф. или др.), мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_5, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_4 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_5.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_25.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_25.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_4.Add(label_25, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        label_26 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_26.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_26.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_4.Add(label_26, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TP_1_1_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_1_1_enabled, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_TP_1_1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TP_1_1.Enable(False)
        self.field_TP_1_1.SetDigits(2)
        grid_sizer_4.Add(self.field_TP_1_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TP_1_2_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.field_TP_1_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TP_1_2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TP_1_2.Enable(False)
        self.field_TP_1_2.SetDigits(2)
        grid_sizer_4.Add(self.field_TP_1_2, 0, wx.EXPAND | wx.RIGHT, 5)

        sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"t прохождения продольных волн (между торцами или др.), мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_13, 1, wx.EXPAND, 0)

        grid_sizer_13 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_13.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        grid_sizer_13.Add((0, 0), 0, 0, 0)

        label_27 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_27.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_27.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_13.Add(label_27, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_13.Add((0, 0), 0, 0, 0)

        label_28 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_28.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_28.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_13.Add(label_28, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TP_2_1_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_13.Add(self.field_TP_2_1_enabled, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.field_TP_2_1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TP_2_1.Enable(False)
        self.field_TP_2_1.SetDigits(2)
        grid_sizer_13.Add(self.field_TP_2_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TP_2_2_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_13.Add(self.field_TP_2_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TP_2_2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TP_2_2.Enable(False)
        self.field_TP_2_2.SetDigits(2)
        grid_sizer_13.Add(self.field_TP_2_2, 0, wx.EXPAND | wx.RIGHT, 5)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"t прохождения поверхностных волн, мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_6, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        grid_sizer_5 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_6.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        label_24 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_24.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_24.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_5.Add(label_24, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_13.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_13.SetToolTip(u"Замер времени прохождения поверхностных волн - 2")
        grid_sizer_5.Add(label_13, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TR_1_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.field_TR_1_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TR_1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TR_1.Enable(False)
        self.field_TR_1.SetDigits(2)
        grid_sizer_5.Add(self.field_TR_1, 0, wx.EXPAND | wx.RIGHT, 5)

        self.field_TR_2_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.field_TR_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TR_2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=10.0)
        self.field_TR_2.Enable(False)
        self.field_TR_2.SetDigits(2)
        grid_sizer_5.Add(self.field_TR_2, 0, wx.EXPAND, 0)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"t прохождения поперечных волн, мс"), wx.HORIZONTAL)
        sizer_10.Add(sizer_7, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        grid_sizer_6 = wx.FlexGridSizer(2, 4, 5, 5)
        sizer_7.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_14.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_14.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_6.Add(label_14, 0, wx.ALIGN_BOTTOM, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_15.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_15.SetToolTip(u"Замер времени прохождения поверхностных волн - 1")
        grid_sizer_6.Add(label_15, 0, wx.ALIGN_BOTTOM, 0)

        self.field_TS_1_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.field_TS_1_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TS_1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_TS_1.Enable(False)
        self.field_TS_1.SetDigits(2)
        grid_sizer_6.Add(self.field_TS_1, 0, wx.EXPAND, 0)

        self.field_TS_2_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.field_TS_2_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_TS_2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0, min=0.0, max=100.0)
        self.field_TS_2.Enable(False)
        self.field_TS_2.SetDigits(2)
        grid_sizer_6.Add(self.field_TS_2, 0, wx.EXPAND, 0)

        grid_sizer_7 = wx.FlexGridSizer(2, 3, 5, 5)
        sizer_4.Add(grid_sizer_7, 1, wx.BOTTOM | wx.EXPAND, 10)

        label_54 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Статич. коэф. Пуассона:")
        label_54.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_54.SetToolTip(u"Статический коэффициент Пуассона")
        grid_sizer_7.Add(label_54, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_PuassonStatic_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_7.Add(self.field_PuassonStatic_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_PuassonStatic = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_PuassonStatic.Enable(False)
        self.field_PuassonStatic.SetDigits(2)
        grid_sizer_7.Add(self.field_PuassonStatic, 0, 0, 0)

        label_55 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Cтатич. модуль Юнга:")
        label_55.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_55.SetToolTip(u"Статический модуль Юнга")
        grid_sizer_7.Add(label_55, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_YungStatic_enabled = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        grid_sizer_7.Add(self.field_YungStatic_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_YungStatic = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_YungStatic.Enable(False)
        self.field_YungStatic.SetDigits(2)
        grid_sizer_7.Add(self.field_YungStatic, 0, 0, 0)

        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Относительная деформация образца"), wx.HORIZONTAL)
        sizer_4.Add(sizer_8, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_8 = wx.GridSizer(2, 4, 5, 5)
        sizer_8.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_16.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_16.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 1")
        grid_sizer_8.Add(label_16, 0, wx.ALIGN_BOTTOM, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_17.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_17.SetToolTip(u"Замер времени прохождения продольных волн (ультразвуковое профилирование или др.) - 2")
        grid_sizer_8.Add(label_17, 0, wx.ALIGN_BOTTOM, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "3")
        label_18.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_18.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 1")
        grid_sizer_8.Add(label_18, 0, wx.ALIGN_BOTTOM, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "4")
        label_19.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_19.SetToolTip(u"Замер времени прохождения продольных волн (между торцами или др.) - 2")
        grid_sizer_8.Add(label_19, 0, wx.ALIGN_BOTTOM, 0)

        self.field_E1 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_E1.SetDigits(2)
        grid_sizer_8.Add(self.field_E1, 0, wx.EXPAND, 0)

        self.field_E2 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_E2.SetDigits(2)
        grid_sizer_8.Add(self.field_E2, 0, wx.EXPAND, 0)

        self.field_E3 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_E3.SetDigits(2)
        grid_sizer_8.Add(self.field_E3, 0, wx.EXPAND, 0)

        self.field_E4 = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_E4.SetDigits(2)
        grid_sizer_8.Add(self.field_E4, 0, wx.EXPAND, 0)

        grid_sizer_9 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_4.Add(grid_sizer_9, 1, wx.BOTTOM | wx.EXPAND, 10)

        label_62 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Угол коррекции направления напряжений, α°:", style=wx.ALIGN_RIGHT)
        label_62.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_62.SetToolTip(u"Угол коррекции направления напряжений, α°")
        label_62.Wrap(150)
        grid_sizer_9.Add(label_62, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Rotate = wx.SpinCtrlDouble(self.panel_1, wx.ID_ANY, initial=0.0, min=0.0, max=100.0)
        self.field_Rotate.SetDigits(2)
        grid_sizer_9.Add(self.field_Rotate, 0, 0, 0)

        label_63 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Тип породы:")
        label_63.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        label_63.SetToolTip(u"Тип породы")
        grid_sizer_9.Add(label_63, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_RockType = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.field_RockType.SetMinSize((200, 23))
        grid_sizer_9.Add(self.field_RockType, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self.main, wx.ID_SAVE, u"Сохранить")
        sizer_2.AddButton(self.button_SAVE)

        self.button_CANCEL = wx.Button(self.main, wx.ID_CANCEL, u"Отмена")
        sizer_2.AddButton(self.button_CANCEL)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY, style=wx.BORDER_NONE | wx.TAB_TRAVERSAL)
        self.notebook_1_pane_2.Enable(False)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"Сопутствующие материалы")

        sizer_2.Realize()

        grid_sizer_6.AddGrowableCol(1)
        grid_sizer_6.AddGrowableCol(3)

        grid_sizer_5.AddGrowableCol(1)
        grid_sizer_5.AddGrowableCol(3)

        grid_sizer_13.AddGrowableCol(1)
        grid_sizer_13.AddGrowableCol(3)

        grid_sizer_4.AddGrowableCol(1)
        grid_sizer_4.AddGrowableCol(3)

        grid_sizer_11.AddGrowableCol(0)
        grid_sizer_11.AddGrowableCol(1)
        grid_sizer_11.AddGrowableCol(2)
        grid_sizer_11.AddGrowableCol(3)

        grid_sizer_1.AddGrowableCol(1)

        self.panel_1.SetSizer(sizer_4)

        self.main.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class Ui_DischargeMeasurement_Editor
