# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Nov  9 05:02:56 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ui_Inspect(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ui_Inspect.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(u"Детальный просмотр")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.list_ctrl_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_SIMPLE | wx.LC_HRULES | wx.LC_NO_HEADER | wx.LC_REPORT)
        self.list_ctrl_1.AppendColumn(u"Поле", format=wx.LIST_FORMAT_LEFT, width=200)
        self.list_ctrl_1.AppendColumn(u"Значение", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_1.Add(self.list_ctrl_1, 1, wx.ALL | wx.EXPAND, 5)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())

        self.Layout()
        # end wxGlade

# end of class Ui_Inspect
