# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Nov  9 05:02:56 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ui_MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ui_MainWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((921, 584))
        self.SetTitle(u"Геомеханика - Поразгрузочные замеры")
        self.SetToolTip(u"БД Геомеханика")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu_sub = wx.Menu()
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Поразгрузочный замер", "")
        self.Bind(wx.EVT_MENU, self.OnCreateDischargeMeasure, item)
        wxglade_tmp_menu_sub.AppendSeparator()
        wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Горный обьект", "")
        item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Серию замеров", "")
        self.Bind(wx.EVT_MENU, self.OnCreateDischargeSeries, item)
        wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"Исходный набор образцов", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, u"Создать", wxglade_tmp_menu_sub, "")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, u"Горные обьекты", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, u"Серии замеров", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, u"Исходные наборы образоцов", "")
        self.frame_menubar.Append(wxglade_tmp_menu, u"Файл")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.frame_statusbar = self.CreateStatusBar(1)
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = ["frame_statusbar"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 5)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(sizer_1, 1, wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 10)

        self.btn_refresh = wx.Button(self, wx.ID_REFRESH, "")
        sizer_1.Add(self.btn_refresh, 0, 0, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Выбрать серию: ")
        sizer_1.Add(label_1, 0, wx.LEFT, 10)

        self.choice_1 = wx.Choice(self, wx.ID_ANY, choices=[u"Все"])
        self.choice_1.SetMinSize((100, 20))
        self.choice_1.SetSelection(0)
        sizer_1.Add(self.choice_1, 0, wx.FIXED_MINSIZE | wx.LEFT | wx.RIGHT, 5)

        self.btn_find = wx.Button(self, wx.ID_ANY, u"Искать")
        self.btn_find.SetDefault()
        sizer_1.Add(self.btn_find, 0, 0, 0)

        self.list_ctrl_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_ctrl_1.AppendColumn("id", format=wx.LIST_FORMAT_LEFT, width=34)
        self.list_ctrl_1.AppendColumn(u"Id серии", format=wx.LIST_FORMAT_LEFT, width=62)
        self.list_ctrl_1.AppendColumn(u"Замер №", format=wx.LIST_FORMAT_LEFT, width=67)
        self.list_ctrl_1.AppendColumn(u"Рег. № разгрузки", format=wx.LIST_FORMAT_LEFT, width=109)
        self.list_ctrl_1.AppendColumn(u"Рег. № керна", format=wx.LIST_FORMAT_LEFT, width=85)
        self.list_ctrl_1.AppendColumn(u"⌀ керна", format=wx.LIST_FORMAT_LEFT, width=57)
        self.list_ctrl_1.AppendColumn(u"L образца керна", format=wx.LIST_FORMAT_LEFT, width=104)
        self.list_ctrl_1.AppendColumn(u"Вес керна", format=wx.LIST_FORMAT_LEFT, width=68)
        self.list_ctrl_1.AppendColumn(u"Тензопатрон №", format=wx.LIST_FORMAT_LEFT, width=98)
        self.list_ctrl_1.AppendColumn(u"Партия тензодатчиков №", format=wx.LIST_FORMAT_LEFT, width=154)
        self.list_ctrl_1.AppendColumn(u"Ω тензорезистора R1, Ом", format=wx.LIST_FORMAT_LEFT, width=152)
        self.list_ctrl_1.AppendColumn(u"Ω тензорезистора R2, Ом", format=wx.LIST_FORMAT_LEFT, width=154)
        self.list_ctrl_1.AppendColumn(u"Ω тензорезистора R3, Ом", format=wx.LIST_FORMAT_LEFT, width=155)
        self.list_ctrl_1.AppendColumn(u"Ω тензорезистора R4, Ом", format=wx.LIST_FORMAT_LEFT, width=155)
        self.list_ctrl_1.AppendColumn(u"Ω компенсаторного резистора, Ом", format=wx.LIST_FORMAT_LEFT, width=206)
        self.list_ctrl_1.AppendColumn(u"Коэф. чувств. тензодатчиков", format=wx.LIST_FORMAT_LEFT, width=171)
        self.list_ctrl_1.AppendColumn(u"t прохождения продольных волн - 1, мс", format=wx.LIST_FORMAT_LEFT, width=233)
        self.list_ctrl_1.AppendColumn(u"t прохождения продольных волн - 2, мс", format=wx.LIST_FORMAT_LEFT, width=235)
        self.list_ctrl_1.AppendColumn(u"t прохождения продольных волн - 3, мс", format=wx.LIST_FORMAT_LEFT, width=236)
        self.list_ctrl_1.AppendColumn(u"t прохождения продольных волн - 4, мс", format=wx.LIST_FORMAT_LEFT, width=236)
        self.list_ctrl_1.AppendColumn(u"t прохождения поверхностных волн - 1, мс", format=wx.LIST_FORMAT_LEFT, width=250)
        self.list_ctrl_1.AppendColumn(u"Замер времени прохождения поверхностных волн - 2, мс", format=wx.LIST_FORMAT_LEFT, width=336)
        self.list_ctrl_1.AppendColumn(u"Замер времени прохождения поперечных волн - 1, мс", format=wx.LIST_FORMAT_LEFT, width=319)
        self.list_ctrl_1.AppendColumn(u"Замер времени прохождения поперечных волн - 2, мс", format=wx.LIST_FORMAT_LEFT, width=316)
        self.list_ctrl_1.AppendColumn(u"Статич. коэф. Пуассона", format=wx.LIST_FORMAT_LEFT, width=143)
        self.list_ctrl_1.AppendColumn(u"Статич. модуль Юнга", format=wx.LIST_FORMAT_LEFT, width=129)
        self.list_ctrl_1.AppendColumn(u"H взятия образца керна", format=wx.LIST_FORMAT_LEFT, width=146)
        self.list_ctrl_1.AppendColumn(u"Относит. деформ. образца - 1", format=wx.LIST_FORMAT_LEFT, width=181)
        self.list_ctrl_1.AppendColumn(u"Относит. деформ. образца - 2", format=wx.LIST_FORMAT_LEFT, width=179)
        self.list_ctrl_1.AppendColumn(u"Относит. деформ. образца - 3", format=wx.LIST_FORMAT_LEFT, width=186)
        self.list_ctrl_1.AppendColumn(u"Относит. деформ. образца - 4", format=wx.LIST_FORMAT_LEFT, width=180)
        self.list_ctrl_1.AppendColumn(u"α коррекции направления напряжений", format=wx.LIST_FORMAT_LEFT, width=228)
        self.list_ctrl_1.AppendColumn(u"Тип породы", format=wx.LIST_FORMAT_LEFT, width=-1)
        grid_sizer_1.Add(self.list_ctrl_1, 0, wx.EXPAND, 0)

        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableCol(0)
        self.SetSizer(grid_sizer_1)

        self.Layout()

        # end wxGlade

    def OnCreateDischargeMeasure(self, event):  # wxGlade: Ui_MainWindow.<event_handler>
        print("Event handler 'OnCreateDischargeMeasure' not implemented!")
        event.Skip()

    def OnCreateDischargeSeries(self, event):  # wxGlade: Ui_MainWindow.<event_handler>
        print("Event handler 'OnCreateDischargeSeries' not implemented!")
        event.Skip()

# end of class Ui_MainWindow
