# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Wed Jan 17 01:10:40 2024
#

import wx


import wx.dataview


class Ui_RelationsViewer(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.tree = wx.dataview.TreeListCtrl(self, wx.ID_ANY)
        sizer_1.Add(self.tree, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

