# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun Jan 14 23:20:34 2024
#

import wx


import wx.dataview


class Ui_SuppliedData_Viewer(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self.SetScrollRate(10, 10)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.FlexGridSizer(2, 1, 5, 5)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        self.button_select_all = wx.Button(self, wx.ID_ANY, u"Выбрать все")
        sizer_3.Add(self.button_select_all, 0, wx.RIGHT, 5)

        self.button_download = wx.Button(self, wx.ID_ANY, u"Скачать")
        self.button_download.Enable(False)
        sizer_3.Add(self.button_download, 0, 0, 0)

        pos = wx.DefaultPosition
        size=wx.DefaultSize
        style = wx.dataview.TL_3STATE
        self.tree = wx.dataview.TreeListCtrl(self, wx.ID_ANY, pos, size, style)
        sizer_2.Add(self.tree, 1, wx.EXPAND, 0)

        sizer_2.AddGrowableRow(1)
        sizer_2.AddGrowableCol(0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

