# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun Jan 14 08:41:52 2024
#

import wx

import wx.adv



class Ui_SuppliedData_Editor(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Наборы"), wx.HORIZONTAL)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(2, 1, 5, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        self.btn_add_data = wx.Button(self, wx.ID_ANY, u"Добавить")
        sizer_3.Add(self.btn_add_data, 0, wx.RIGHT, 5)

        self.btn_edit_data = wx.Button(self, wx.ID_ANY, u"Редактировать")
        self.btn_edit_data.Enable(False)
        sizer_3.Add(self.btn_edit_data, 0, wx.RIGHT, 5)

        self.btn_delete_data = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.btn_delete_data.Enable(False)
        sizer_3.Add(self.btn_delete_data, 0, 0, 0)

        self.list_data = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_data.AppendColumn(u"Название", format=wx.LIST_FORMAT_LEFT, width=300)
        grid_sizer_2.Add(self.list_data, 1, wx.EXPAND, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Файлы набора"), wx.HORIZONTAL)
        grid_sizer_1.Add(sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(2, 1, 5, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        self.btn_add_part = wx.Button(self, wx.ID_ANY, u"Добавить")
        sizer_4.Add(self.btn_add_part, 0, wx.RIGHT, 5)

        self.btn_edit_part = wx.Button(self, wx.ID_ANY, u"Редактировать")
        self.btn_edit_part.Enable(False)
        sizer_4.Add(self.btn_edit_part, 0, wx.RIGHT, 5)

        self.btn_delete_part = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.btn_delete_part.Enable(False)
        sizer_4.Add(self.btn_delete_part, 0, 0, 0)

        self.list_parts = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_parts.AppendColumn(u"Название", format=wx.LIST_FORMAT_LEFT, width=350)
        self.list_parts.AppendColumn(u"Размер", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_parts.AppendColumn(u"Тип", format=wx.LIST_FORMAT_LEFT, width=-1)
        grid_sizer_3.Add(self.list_parts, 1, wx.EXPAND, 0)

        grid_sizer_3.AddGrowableRow(1)
        grid_sizer_3.AddGrowableCol(0)

        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableCol(0)

        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableCol(0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)

        self.Layout()


class UI_DataEditor_Dialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 419))
        self.SetTitle(u"Добавить/Редактировать сопутствующий материал")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.FlexGridSizer(4, 3, 5, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 5)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Номер:")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Number_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Number_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Number = wx.TextCtrl(self, wx.ID_ANY, "")
        self.field_Number.Enable(False)
        grid_sizer_1.Add(self.field_Number, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Название:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.field_Name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Name, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"Комментарий:")
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, u"Датировка материала (официальная):")
        label_4.Wrap(150)
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_DataDate_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_DataDate_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_DataDate = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.field_DataDate.Enable(False)
        grid_sizer_1.Add(self.field_DataDate, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self, wx.ID_ANY, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_2.Add(self.button_SAVE, 0, 0, 0)

        self.button_CANCEL = wx.Button(self, wx.ID_ANY, u"Отмена")
        sizer_2.Add(self.button_CANCEL, 0, 0, 0)

        sizer_2.Realize()

        grid_sizer_1.AddGrowableCol(2)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_SAVE.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()


class Ui_DataPartsEditor_Dialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 419))
        self.SetTitle(u"Добавить/Редактировать сопутствующий материал")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.FlexGridSizer(6, 3, 5, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 5)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Название:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.field_Name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Name, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"Комментарий:")
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.RIGHT, 0)

        self.field_Comment_enabled = wx.CheckBox(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.field_Comment_enabled, 0, wx.ALIGN_CENTER, 0)

        self.field_Comment = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.field_Comment.Enable(False)
        grid_sizer_1.Add(self.field_Comment, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, u"Датировка материала (официальная):")
        label_4.Wrap(150)
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.field_DataDate = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        grid_sizer_1.Add(self.field_DataDate, 0, 0, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Файл:")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        self.file_path = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_3.Add(self.file_path, 0, wx.EXPAND, 0)

        self.button_select_file = wx.Button(self, wx.ID_ANY, u"…")
        self.button_select_file.SetMinSize((30, 20))
        sizer_3.Add(self.button_select_file, 0, 0, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, u"Тип файла:")
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.file_mime_type = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.file_mime_type, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, u"Название файла:")
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.file_name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.file_name, 0, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_SAVE = wx.Button(self, wx.ID_ANY, u"Сохранить")
        self.button_SAVE.SetDefault()
        sizer_2.Add(self.button_SAVE, 0, 0, 0)

        self.button_CANCEL = wx.Button(self, wx.ID_ANY, u"Отмена")
        sizer_2.Add(self.button_CANCEL, 0, 0, 0)

        sizer_2.Realize()

        sizer_3.AddGrowableCol(0)

        grid_sizer_1.AddGrowableCol(2)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_SAVE.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

