# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Tue Jan  9 05:19:24 2024
#

import wx




class Ui_TreeView(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)

        grid_sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Управление"), wx.HORIZONTAL)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 10)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.btn_Add = wx.Button(self, wx.ID_ANY, u"Добавить")
        sizer_2.Add(self.btn_Add, 0, wx.RIGHT, 5)

        self.btn_Edit = wx.Button(self, wx.ID_ANY, u"Редактировать")
        self.btn_Edit.Enable(False)
        sizer_2.Add(self.btn_Edit, 0, wx.RIGHT, 5)

        self.btn_Delete = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.btn_Delete.Enable(False)
        sizer_2.Add(self.btn_Delete, 0, 0, 0)

        self.tree = wx.TreeCtrl(self, wx.ID_ANY)
        sizer_1.Add(self.tree, 1, wx.EXPAND, 0)

        sizer_1.AddGrowableRow(1)
        sizer_1.AddGrowableCol(0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

