#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Tue Jan  9 00:12:17 2024
#

import wx




class UI_ExportWizard(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((421, 514))
        self.SetTitle(u"Мастер экспорта таблиц")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.FlexGridSizer(4, 1, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 5)

        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_2.Add(grid_sizer_1, 1, wx.BOTTOM | wx.EXPAND, 5)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Экспортировать как:")
        grid_sizer_1.Add(label_1, 0, 0, 0)

        self.field_export_type = wx.Choice(self.panel_1, wx.ID_ANY, choices=["CSV", "XLS"])
        self.field_export_type.SetSelection(0)
        grid_sizer_1.Add(self.field_export_type, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Файл:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_RIGHT, 0)

        sizer_6 = wx.FlexGridSizer(1, 2, 0, 5)
        grid_sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)

        self.field_file_name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_6.Add(self.field_file_name, 0, wx.EXPAND, 0)

        self.btn_SelectFile = wx.Button(self.panel_1, wx.ID_ANY, u"…")
        self.btn_SelectFile.SetMinSize((30, 20))
        sizer_6.Add(self.btn_SelectFile, 0, wx.ALIGN_CENTER, 0)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Столбцы"), wx.VERTICAL)
        sizer_2.Add(sizer_5, 1, wx.BOTTOM | wx.EXPAND, 5)

        self.btn_select_all_cols = wx.Button(self.panel_1, wx.ID_ANY, u"Выбрать все")
        sizer_5.Add(self.btn_select_all_cols, 0, wx.ALIGN_RIGHT, 0)

        self.columns = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=[])
        self.columns.SetMinSize((384, 130))
        sizer_5.Add(self.columns, 0, wx.EXPAND, 0)

        self.table = wx.ListCtrl(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        sizer_2.Add(self.table, 1, wx.BOTTOM | wx.EXPAND, 5)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"Экспортирование"), wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.BOTTOM | wx.EXPAND, 10)

        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 5)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.export_progress = wx.Gauge(self.panel_1, wx.ID_ANY, 10)
        grid_sizer_2.Add(self.export_progress, 0, wx.EXPAND, 0)

        self.btn_export = wx.Button(self.panel_1, wx.ID_ANY, u"Экспортировать")
        grid_sizer_2.Add(self.btn_export, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(0)

        sizer_6.AddGrowableCol(0)

        grid_sizer_1.AddGrowableCol(1)

        sizer_2.AddGrowableRow(1)
        sizer_2.AddGrowableRow(2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()


class MyApp(wx.App):
    def OnInit(self):
        self.UI_ExportWizard = UI_ExportWizard(None, wx.ID_ANY, "")
        self.SetTopWindow(self.UI_ExportWizard)
        self.UI_ExportWizard.Show()
        return True

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
