# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Fri Jul  5 02:07:47 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ui_CsTransl(wx.Frame):
    def __init__(self, parent, size=wx.DefaultSize):
        # begin wxGlade: Ui_CsTransl.__init__
        wx.Frame.__init__(
            self,
            parent,
            style=wx.DEFAULT_FRAME_STYLE & ~wx.MAXIMIZE_BOX | wx.FRAME_FLOAT_ON_PARENT,
        )
        self.SetTitle("Пересчет координат")
        self.SetBackgroundColour(wx.NullColour)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.FlexGridSizer(1, 2, 5, 5)
        sizer_2.Add(sizer_3, 0, wx.ALL | wx.EXPAND, 10)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Из:")
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.choce_from = wx.Choice(self, wx.ID_ANY, choices=[])
        sizer_3.Add(self.choce_from, 1, wx.EXPAND, 10)

        self.sizer_from = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Исходные координаты"), wx.HORIZONTAL)
        sizer_2.Add(self.sizer_from, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        self.sizer_from.Add(grid_sizer_1, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        label_2 = wx.StaticText(self, wx.ID_ANY, "X:")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_X_from = wx.SpinCtrlDouble(
            self,
            wx.ID_ANY,
            initial=0.0,
            min=-100000000.0,
            max=10000000000.0,
            style=wx.SP_ARROW_KEYS | wx.TE_PROCESS_ENTER,
        )
        self.field_X_from.Enable(False)
        self.field_X_from.SetDigits(2)
        grid_sizer_1.Add(self.field_X_from, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, "Y:")
        label_3.Enable(False)
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Y_from = wx.SpinCtrlDouble(
            self,
            wx.ID_ANY,
            initial=0.0,
            min=-100000000.0,
            max=10000000000.0,
            style=wx.SP_ARROW_KEYS | wx.TE_PROCESS_ENTER,
        )
        self.field_Y_from.Enable(False)
        self.field_Y_from.SetDigits(2)
        grid_sizer_1.Add(self.field_Y_from, 0, wx.EXPAND, 0)

        sizer_5 = wx.FlexGridSizer(1, 2, 5, 5)
        sizer_2.Add(sizer_5, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        label_10 = wx.StaticText(self, wx.ID_ANY, "В:")
        sizer_5.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.choice_to = wx.Choice(self, wx.ID_ANY, choices=[])
        sizer_5.Add(self.choice_to, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        sizer_to = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Результат"), wx.HORIZONTAL)
        sizer_2.Add(sizer_to, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        grid_sizer_2 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_to.Add(grid_sizer_2, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        label_5 = wx.StaticText(self, wx.ID_ANY, "X:")
        grid_sizer_2.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_X_to = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=-100000000.0, max=10000000000.0)
        self.field_X_to.Enable(False)
        self.field_X_to.SetDigits(2)
        grid_sizer_2.Add(self.field_X_to, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, "Y:")
        grid_sizer_2.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.field_Y_to = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.0, min=-100000000.0, max=10000000000.0)
        self.field_Y_to.Enable(False)
        self.field_Y_to.SetDigits(2)
        grid_sizer_2.Add(self.field_Y_to, 0, wx.EXPAND, 0)

        sizer_4 = wx.StdDialogButtonSizer()
        sizer_2.Add(sizer_4, 0, wx.ALIGN_RIGHT | wx.ALL, 10)

        self.btn_calc = wx.Button(self, wx.ID_ANY, "Посчитать")
        self.btn_calc.SetDefault()
        sizer_4.Add(self.btn_calc, 0, 0, 0)

        sizer_4.Realize()

        grid_sizer_2.AddGrowableCol(1)

        sizer_5.AddGrowableCol(1)

        grid_sizer_1.AddGrowableCol(1)

        sizer_3.AddGrowableCol(1)

        self.SetSizer(sizer_2)
        sizer_2.SetSizeHints(self)
        # end wxGlade


# end of class Ui_CsTransl
